version: build-{build}
max_jobs: 1
image: Visual Studio 2022
clone_folder: C:\prj\deca

build_script:
- cmd: >-
    SET PATH=C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%

    echo GET SUBMODULES

    cd C:\prj\deca

    git config submodule.extern/HavokLib.url https://github.com/kk49/HavokLib.git

    git submodule update --init --recursive

    echo PATCH external libs

    cd C:\prj\deca\extern\HavokLib\3rd_party\PreCore

    git apply C:\prj\deca\patch\pre_core.patch

    echo BUILD C++

    call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"

    mkdir C:\prj\deca\build

    cd C:\prj\deca\build

    cmake -DPython3_ROOT_DIR=C:\Python38-x64 -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ..

    nmake

    mkdir C:\prj\deca\root\bin

    mkdir C:\prj\deca\root\lib

    copy C:\prj\deca\build\cpp\bin2xml\bin2xml* C:\prj\deca\root\bin\ 

    copy C:\prj\deca\build\cpp\process_image\process_image* C:\prj\deca\root\lib\ 

    echo SETUP PYTHON

    cd C:\prj\deca

    c:\Python38-x64\python --version

    c:\Python38-x64\python -m pip list

    c:\Python38-x64\python -m venv venv

    venv\Scripts\activate

    pip install -r python/requirements.txt

    pip install wheel requests pyinstaller -e python/deca/ -e python/deca_gui/

    echo PACKAGE

    cd C:\prj\deca

    pyinstaller deca_gui.spec --clean --noconfirm --distpath dist --workpath build_py 

after_build:
  - cmd: >
      cd dist\deca_gui
      7z a ..\..\deca_gui-b%APPVEYOR_BUILD_NUMBER%.zip *

artifacts:
- path: deca_gui-b%APPVEYOR_BUILD_NUMBER%.zip
  name: deca_gui-b%APPVEYOR_BUILD_NUMBER%.zip

deploy:
  provider: GitHub
  artifact: deca_gui-b%APPVEYOR_BUILD_NUMBER%.zip
  prerelease: true
  description: 'Test Release'
  auth_token:
    secure: BUTLxoG2hdtUup+JV4auiE1zuaBvpnIywQTDw6YAmzcIB05UU4cFHAJp8JtzW2D6
  tag: build-{build}  # Tag associated with the release
  on:
    APPVEYOR_REPO_TAG: true  # Deploy on tag push only

on_success:
  - ps: |
      cd C:\prj\deca
      python ./appveyor/on_success.py success CHANGELOG.md $env:BUILD_WEBHOOK_URL
